title: M Divyadarshini
logo: assets/image/divya_rectangle_headshot.jpg
description: >
  PhD Scholar in Deep Learning | ML Engineer with (2+ years) in designing model architcture, model optimization and deployment.
show_downloads: false
theme: jekyll-theme-minimal
